# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f8065e77a5fc6c6c0735139a02524be9815b08375be7679f9b2d78fce3b3292074ce2a2ea4029319b6a47ef58d394c602e53419262164f1f185d04bb50fb311

test:
  secret_key_base: 8556a091f5fe20adecce2c881e5d557c56c023c011ec5aab182942fed3a45cfa7a5c9ed60a71ec24765684f510c4371d2295f7ae2170bc7e480cef33d8ff4448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
